// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      // case TargetPlatform.android:
      //   return android;
      // case TargetPlatform.iOS:
      //   return ios;
      // case TargetPlatform.macOS:
      //   return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTzscstZsBRovefyK6JoNjHyLxoYN-7IY',
    appId: '1:1023746513206:web:e6613be2411a9e76c43b97',
    messagingSenderId: '1023746513206',
    projectId: 'shopper-89651',
    authDomain: 'shopper-89651.firebaseapp.com',
    storageBucket: 'shopper-89651.appspot.com',
    measurementId: 'G-DLR5JDEYKM',
  );

  // static const FirebaseOptions android = FirebaseOptions(
  //   apiKey: 'AIzaSyCaihht30uCJAAhmyV4FzbPUg2TZZ8OrNY',
  //   appId: '1:1023746513206:android:ff5bd0748de57b2ac43b97',
  //   messagingSenderId: '1023746513206',
  //   projectId: 'shopper-89651',
  //   storageBucket: 'shopper-89651.appspot.com',
  // );

  // static const FirebaseOptions ios = FirebaseOptions(
  //   apiKey: 'AIzaSyCkbiBIbFQAaW-XkJST4coI8pkCwv40uH0',
  //   appId: '1:1023746513206:ios:7f374534cc82d74ec43b97',
  //   messagingSenderId: '1023746513206',
  //   projectId: 'shopper-89651',
  //   storageBucket: 'shopper-89651.appspot.com',
  //   iosClientId: '1023746513206-kq39bcqi3c2dngcgh4v3o0g75dgq1mvs.apps.googleusercontent.com',
  //   iosBundleId: 'com.example.shopperProjects',
  // );

  // static const FirebaseOptions macos = FirebaseOptions(
  //   apiKey: 'AIzaSyCkbiBIbFQAaW-XkJST4coI8pkCwv40uH0',
  //   appId: '1:1023746513206:ios:7f374534cc82d74ec43b97',
  //   messagingSenderId: '1023746513206',
  //   projectId: 'shopper-89651',
  //   storageBucket: 'shopper-89651.appspot.com',
  //   iosClientId: '1023746513206-kq39bcqi3c2dngcgh4v3o0g75dgq1mvs.apps.googleusercontent.com',
  //   iosBundleId: 'com.example.shopperProjects',
  // );
}
